"""add tags and blogs relation

Revision ID: a6f6d00d0129
Revises: c044d4b7c5f3
Create Date: 2026-02-11 17:11:18.529854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f6d00d0129'
down_revision: Union[str, Sequence[str], None] = 'c044d4b7c5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_blog_tags',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blog_id'], ['tbl_blogs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tbl_tags.id'], ),
    sa.PrimaryKeyConstraint('blog_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_blog_tags')
    # ### end Alembic commands ###
