"""add user and blog relation

Revision ID: c044d4b7c5f3
Revises: e66fc85b1251
Create Date: 2026-02-10 21:49:49.589078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c044d4b7c5f3'
down_revision: Union[str, Sequence[str], None] = 'e66fc85b1251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_blogs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tbl_blogs', 'tbl_users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_blogs', type_='foreignkey')
    op.drop_column('tbl_blogs', 'user_id')
    # ### end Alembic commands ###
